### ISSUE TITLE
Question about TSM result 

### ISSUE THREAD

**Issue by gd2016229035** [V-Sense/ACTION-Net#5]
In Jester dataset, TSM result in Table 1 of your paper is 94.4 (ResNet50 8frame 3crop 10clip), 
But TSM result in origin paper(Table 1) is 97.0 (ResNet50 8frame  full-resolution 2clips ). 
I test the TSM by myself from the TSM official public code and it can also reach 97.0.
How cause this Gap between 94.4 and 97.0?

**Comment by villawang** [comment]
> In Jester dataset, TSM result in Table 1 of your paper is 94.4 (ResNet50 8frame 3crop 10clip),
> But TSM result in origin paper(Table 1) is 97.0 (ResNet50 8frame full-resolution 2clips ).
> I test the TSM by myself from the TSM official public code and it can also reach 97.0.
> How cause this Gap between 94.4 and 97.0?

Hi there, thanks for your question. We just directly use the result in [STM paper](https://openaccess.thecvf.com/content_ICCV_2019/papers/Jiang_STM_SpatioTemporal_and_Motion_Encoding_for_Action_Recognition_ICCV_2019_paper.pdf) in Table 2. I guess it might be caused by using different training augmentation strategies.
